version: "3.7"
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - PD_DB_NAME=${PD_DB_NAME}
      - PD_DB_PORT=${PD_DB_PORT}
      - PD_DB_USER=${PD_DB_USER}
      - PD_DB_HOST=${PD_DB_HOST}
      - PD_DB_PASSWORD=${PD_DB_PASSWORD}
