version: "3.7"
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/db/migrations/001_initial.sql:/docker-entrypoint-initdb.d/001_initial.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - 5432:5432

volumes:
  postgres_data:
